#-------------------------------
# General Site Settings

menus:
- {name: 'Chi sono', url: '#chi-sono'}
- {name: 'Il centro', url: '#il-centro'}
- {name: 'Prodotti', url: '#special'}
- {name: 'Servizi', url: '#servizi'}
- {name: 'Contatti', url: '#contatti'}

#-------------------------------
# Certifications

certifications:
- {name: 'Diploma BCM Milano',
  icon: '',
  image: ''}
- {name: 'Diploma Pandhys',
  icon: '',
  image: ''}
- {name: 'Diploma PNEI',
  icon: '',
  image: ''}
- {name: 'Diploma Crystal Nails',
  icon: '',
  image: ''}

#-------------------------------
# Orari

times:
- {name: 'Lunedì', morning: '-', afternoon: '-'}
- {name: 'Martedì', morning: '09:00 - 12:30', afternoon: '13:30 - 19:00'}
- {name: 'Mercoledì', morning: '09:00 - 12:30', afternoon: '13:30 - 19:00'}
- {name: 'Giovedì', morning: '09:00 - 12:30', afternoon: '13:30 - 20:00'}
- {name: 'Venerdì', morning: '09:00 - 12:30', afternoon: '13:30 - 19:00'}
- {name: 'Sabato', morning: '09:00 - 13:00', afternoon: '-'}
